export const supportedAddresses = {
  Lagos: [
    "Abule Egba, Agbado Ijaye Road",
    "Abule Egba, Ajasa Command Rd",
    "Abule Egba, Ajegunle",
    "Abule Egba, Alagbado",
    "Abule Egba, Alakuko",
    "Abule Egba, Ekoro road",
    "Abule Egba, Meiran Road",
    "Abule Egba, New Oko Oba",
    "Abule Egba, Old Otta Road",
    "Agbara",
    "Agege, Dopemu",
    "Agege, Iju Road",
    "Agege, Old Abeokuta Road",
    "Agege, Orile Agege",
    "AGUNGI, LEKKI",
    "Ajah, Abraham Adesanya",
    "AJAO ESTATE",
    "AMUWO",
    "ANTHONY VILLAGE",
    "Apapa, Ajegunle",
    "Apapa, Amukoko",
    "Apapa, GRA",
    "Apapa, Kiri kiri",
    "Apapa, Olodi",
    "Apapa, Tincan",
    "Apapa, Warf Rd",
    "AWOYAYA",
    "Awoyaya, Container bustop",
    "Awoyaya, Eputu",
    "Awoyaya, Gbetu Iwerekun Road",
    "Awoyaya, Mayfair Gardens",
    "Awoyaya, Ologunfe",
    "Awoyaya, Oribanwa",
    "Badagry",
    "BERGER",
    "Bogije",
    "Coker",
    "Egbeda, Shasha",
    "Ejigbo, Bucknor",
    "Ejigbo, Ile Epo",
    "Ejigbo, Isheri Osun",
    "Ejigbo, Jakande Wood Market",
    "Ejigbo, NNPC Road",
    "Ejigbo, Oke Afa",
    "Ejigbo, Pipeline",
    "Ejigbo, Powerline",
    "EPE",
    "Fagba, Iju Road",
    "FESTAC, 1st Avenue",
    "FESTAC, 2nd Avenue",
    "FESTAC, 3rd Avenue",
    "FESTAC, 5th Avenue",
    "FESTAC, 7th Avenue",
    "Gbagada, Ifako",
    "Gbagada, Deeper Life",
    "Gbagada, Expressway",
    "Gbagada, L&K",
    "Gbagada, New Garage",
    "Gbagada, Olopomeji",
    "Gbagada, Pedro",
    "Gbagada, Sawmill",
    "Gbagada, Sholuyi",
    "Ibeju Lekki, Dangote Refinery",
    "Ibeju Lekki, Eleko Junction",
    "Ibeju Lekki, Pan African University",
    "IDIMU",
    "IGANDO",
    "IJANIKIN",
    "IJEGUN IKOTUN",
    "IJORA",
    "Ikeja, ADENIYI JONES",
    "Ikeja, ALAUSA",
    "Ikeja, ALLEN AVENUE",
    "Ikeja, computer village",
    "Ikeja, GRA",
    "IKEJA, M M Airport",
    "Ikeja, MANGORO",
    "Ikeja, OBA AKRAN",
    "Ikeja, OPEBI",
    "IKORODU, Adamo",
    "IKORODU, Agbede",
    "IKORODU, Agric",
    "IKORODU, Bayeku",
    "IKORODU, Eyita",
    "IKORODU, Gberigbe",
    "IKORODU, Ijede",
    "IKORODU, Imota",
    "IKORODU, Ita oluwo",
    "IKORODU, Itamaga",
    "IKORODU, Offin",
    "IKORODU, Owode Ibese",
    "Ikorodu Road, Irawo",
    "Ikorodu Road, Owode Onirin",
    "IKORODU, Elepe",
    "IKORODU, Laspotech",
    "Ikorodu, Ogolonto",
    "IKORODU, Sabo",
    "Ikorodu, Agufoye",
    "Ikorodu, Benson",
    "Ikorodu, Garage",
    "Ikorodu, Odokekere",
    "Ikorodu, Odonla",
    "Ikorodu, Ogijo",
    "IKOTA",
    "IKOTUN",
    "Ikoyi, Awolowo Road",
    "Ikoyi, Bourdillon",
    "Ikoyi, Dolphin",
    "Ikoyi, Glover road",
    "Ikoyi, Keffi",
    "Ikoyi, Kings way road",
    "Ikoyi, Obalende",
    "Ikoyi, Parkview",
    "ILAJE, BARIGA",
    "ILUPEJU, Lagos",
    "ISHERI IKOTUN",
    "ISHERI MAGODO",
    "ISOLO",
    "Isolo, Laspotech",
    "IYANA IBA",
    "Iyana Ipaja, Abesan",
    "Iyana Ipaja, Aboru",
    "Iyana Ipaja, Ayobo Road",
    "Iyana Ipaja, Command Road",
    "Iyana Ipaja, Egbeda",
    "Iyana Ipaja, Ikola Road",
    "Iyana Ipaja, Iyana Ipaja Road",
    "Iyana Ipaja, Shasha",
    "JAKANDE, LEKKI",
    "JANKANDE, ISOLO",
    "Ketu, Alapere",
    "Ketu, CMD road",
    "Ketu, Demurin",
    "Ketu, Ikosi Road",
    "Ketu, Iyana School",
    "Lagos Island, Adeniji",
    "Lagos Island, Marina",
    "Lagos Island, Onikan",
    "Lagos Island, Sura",
    "Lagos Island, TBS",
    "Lakowe, Adeba Road",
    "Lakowe, Golf",
    "Lakowe, Kajola",
    "Lakowe, School Gate",
    "LEKKI, VGC",
    "Lekki 1, Bishop Durosimi",
    "Lekki 1, F.T Kuboye street",
    "Lekki 1, Omorinre Johnson",
    "Lekki Phase 1, Admiralty Road",
    "Lekki Phase 1, Admiralty way",
    "Lekki Phase 1, Fola Osibo",
    "LEKKI, AGUNGI",
    "LEKKI AJAH, ABIJO",
    "LEKKI AJAH, ADDO ROAD",
    "LEKKI AJAH, BADORE",
    "LEKKI AJAH, ILAJE",
    "LEKKI AJAH, ILASAN",
    "LEKKI AJAH, JAKANDE",
    "LEKKI AJAH, SANGOTEDO",
    "Lekki, Chisco",
    "LEKKI, ELF",
    "LEKKI, IGBOEFON",
    "LEKKI, IKATE ELEGUSHI",
    "LEKKI, MARUWA",
    "LEKKI, ONIRU ESTATE",
    "LEKKI, OSAPA LONDON",
    "Magboro",
    "MAGODO",
    "MARYLAND, MENDE",
    "MARYLAND, ONIGBONGBO",
    "MILE 12",
    "Mile 12, Ajelogo",
    "MILE 2",
    "Mushin, Palm Avenue",
    "Mushin, Agege Motor Road",
    "Mushin, Daleko Market",
    "Mushin, Fatai Atere",
    "Mushin, Idi Oro",
    "Mushin, Idi Araba",
    "Mushin, Ilasamaja Road",
    "Mushin, Ladipo Road",
    "Mushin, Olateju",
    "Mushin, Papa Ajao",
    "Ogba, Akilo Road",
    "Ogba, College Road",
    "Ogba, Acme Road",
    "Ogba, Aguda",
    "Ogba, Obawole",
    "Ogba, Ojodu",
    "Ogba, Oke Ira",
    "Ogba, Wemco Road",
    "OGUDU",
    "Ojo, Ajangbadi",
    "Ojo, Alaba International",
    "Ojo, Alakija",
    "Ojo, Ojo Barracks",
    "Ojo, Okokomaiko",
    "Ojo, PPL",
    "Ojo, Trade Fair",
    "OJODU",
    "OJOKORO",
    "OJOTA",
    "OKOKOMAIKO",
    "OKOTA",
    "Omole Phase 1",
    "Omole Phase 2",
    "Oniru",
    "OREGUN",
    "ORILE",
    "OSAPA, LEKKI",
    "OSHODI, BOLADE",
    "OSHODI, ISOLO",
    "OSHODI, MAFOLUKU",
    "OSHODI, SHOGUNLE",
    "Satelite Town",
    "SOMOLU",
    "Surulere, Adeniran Ogunsanya",
    "Surulere, Aguda",
    "Surulere, Bode Thomas",
    "Surulere, Idi Araba",
    "Surulere, Ijesha",
    "Surulere, Iponri",
    "Surulere, Itire",
    "Surulere, Lawanson",
    "Surulere, Masha",
    "Surulere, Ogunlana drive",
    "Surulere, Ojuelegba",
    "VI, Adetokunbo Ademola",
    "VI, Ahmed Bello way",
    "VI, Bishop Aboyade Cole",
    "VI, Oniru Road",
    "VI, Ajose Adeogun",
    "VI, Akin Adeshola",
    "VI, Bishop Oluwale",
    "Victoria Island, Adeola Odeku",
    "Victoria Island, Kofo Abayomi",
    "Yaba, Abule Ijesha",
    "Yaba, Fadeyi",
    "Yaba, Sabo",
    "Yaba, Unilag",
    "Yaba, Abule Oja",
    "Yaba, Adekunle",
    "Yaba, Akoka",
    "Yaba, Alagomeju",
    "Yaba, Folagoro",
    "Yaba, Herbert Macaulay Way",
    "Yaba, Jibowu",
    "Yaba, Onike Iwaya",
    "Yaba, Oyingbo",
    "Yaba, Tejuosho",
    "Yaba, University Road",
    "Yaba, Yabatech",
  ],

  Oyo: [
    "APETE",
    "EGBEDA, Oyo",
    "Ibadan, Agodi",
    "IBADAN, AKOBO",
    "IBADAN, ALAKIA",
    "IBADAN, APATA",
    "IBADAN, BODIJA",
    "IBADAN, DUGBE",
    "IBADAN, ELEBU",
    "IBADAN, ELEYELE",
    "IBADAN, FELELE",
    "Ibadan, Idi ape, Ashi",
    "IBADAN, IWO ROAD",
    "IBADAN, JERICHO",
    "Ibadan, Leadcity",
    "IBADAN, MOLETE",
    "Ibadan, Monantan",
    "Ibadan, Moniya",
    "IBADAN, NEW GARAGE",
    "Ibadan, North West",
    "IBADAN, OJOO",
    "Ibadan, Olodo",
    "Ibadan, Olorunsogo",
    "IBADAN, OLUYOLE",
    "Ibadan, Orita, Challenge",
    "IBADAN, RING ROAD",
    "Ibadan, Soka",
    "Ibadan, UI",
    "LALUPON",
    "Ogbomosho",
    "OWODE, OYO",
    "Oyo Town, New Cele",
    "Oyo Town, Oroki",
  ],

  Ogun: [
    "Abeokuta",
    "Agbara, OPIC",
    "AGO IWOYE",
    "AKUTE",
    "IJEBU IGBO",
    "Ijebu Ode Folagbade",
    "Ilaro-Oke Odan",
    "Ilishan Remo-babcock",
    "Iperu Remo",
    "Mowe Ibafo",
    "OTTA TOWN, BELLS",
    "OTTA TOWN, IFO",
    "Sagamu, Akarigbo",
    "SANGO, IJOKO",
    "SANGO OTTA, ATAN",
    "SANGO OTTA, OJU ORE",
  ],
};
