export const productCategories = [
  {
    name: "Foodstuffs",
    subcategories: [
      "Grains & Cereals",
      "Flours",
      "Legumes & Pulses",
      "Spices & Seasonings",
      "Cooking Oils",
      "Meat & Poultry",
      "Seafood",
      "Dairy Products",
    ],
  },
  {
    name: "Groceries",
    subcategories: [
      "Beverages",
      "Snacks",
      "Canned & Jarred Foods",
      "Condiments & Sauces",
      "Pasta & Noodles",
      "Baking Ingredients",
      "Breakfast Cereals",
      "Packaged Meals",
    ],
  },
  {
    name: "Fruits & Vegetables",
    subcategories: [
      "Fresh Fruits",
      "Fresh Vegetables",
      "Herbs & Spices",
      "Frozen Fruits",
      "Frozen Vegetables",
    ],
  },
  {
    name: "Health & Personal Care",
    subcategories: [
      "Vitamins & Supplements",
      "Skincare",
      "Haircare",
      "Oral Care",
      "First Aid Supplies",
      "Men's Grooming",
      "Feminine Care",
    ],
  },
  {
    name: "Household Supplies",
    subcategories: [
      "Cleaning Supplies",
      "Laundry Essentials",
      "Toilet Paper & Tissues",
      "Trash Bags",
      "Air Fresheners",
      "Pest Control",
    ],
  },
  {
    name: "Electronics",
    subcategories: [
      "Mobile Phones & Accessories",
      "Laptops & Computers",
      "Cameras",
      "Audio Equipment",
      "Smart Home Devices",
      "Gaming Consoles",
    ],
  },
  {
    name: "Clothing & Accessories",
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      "Footwear",
      "Jewelry",
      "Bags & Wallets",
    ],
  },
  {
    name: "Home & Kitchen",
    subcategories: [
      "Kitchen Appliances",
      "Cookware & Utensils",
      "Home Decor",
      "Furniture",
      "Bedding & Linens",
      "Storage & Organization",
    ],
  },
  {
    name: "Toys & Games",
    subcategories: [
      "Action Figures",
      "Educational Toys",
      "Board Games",
      "Outdoor Toys",
      "Puzzles",
      "Video Games",
    ],
  },
  {
    name: "Books & Stationery",
    subcategories: [
      "Fiction",
      "Non-Fiction",
      "Children's Books",
      "Academic Texts",
      "Notebooks",
      "Art Supplies",
    ],
  },
  {
    name: "Sports & Outdoors",
    subcategories: [
      "Fitness Equipment",
      "Outdoor Gear",
      "Team Sports",
      "Cycling",
      "Camping & Hiking",
      "Water Sports",
    ],
  },
  {
    name: "Automotive",
    subcategories: [
      "Car Accessories",
      "Motorbike Accessories",
      "Car Care Products",
      "Spare Parts",
      "Tires & Wheels",
      "Oils & Fluids",
    ],
  },
  {
    name: "Health Foods",
    subcategories: [
      "Organic Foods",
      "Gluten-Free Foods",
      "Protein Bars",
      "Energy Drinks",
      "Dried Fruits & Nuts",
      "Herbal Teas",
    ],
  },
  {
    name: "Pet Supplies",
    subcategories: [
      "Pet Food",
      "Pet Toys",
      "Pet Grooming",
      "Pet Beds",
      "Aquariums & Accessories",
      "Leashes & Collars",
    ],
  },
  {
    name: "Others",
    subcategories: [
      "Gift Items",
      "Souvenirs & Collectibles",
      "Religious Items",
      "Party Supplies",
      "Safety & Security Gadgets",
      "Arts & Crafts",
      "DIY Tools & Materials",
      "Seasonal Decorations",
      "Office Furniture",
      "Tickets & Vouchers",
      "Musical Instruments",
      "Event Equipment",
      "Industrial Products",
      "Services",
      "Miscellaneous Accessories",
      "Others",
    ],
  },
];

export const serviceCategories = [
  {
    name: "Home Services",
    subcategories: [
      "Plumbing",
      "Electrician",
      "House Cleaning",
      "Pest Control",
      "Carpentry",
      "Painting",
      "Appliance Repair",
    ],
  },
  {
    name: "Health & Wellness",
    subcategories: [
      "Massage Therapy",
      "Fitness Training",
      "Dietitian/Nutritionist",
      "Yoga Instructor",
      "Mental Health Counseling",
    ],
  },
  {
    name: "Automotive Services",
    subcategories: [
      "Car Repair",
      "Car Wash/Detailing",
      "Tire Services",
      "Battery Replacement",
      "Oil Change",
    ],
  },
  {
    name: "Personal Care",
    subcategories: [
      "Haircut/Styling",
      "Makeup Services",
      "Nail Services",
      "Spa Services",
      "Tattooing",
    ],
  },
  {
    name: "Education",
    subcategories: [
      "Tutoring",
      "Music Lessons",
      "Language Classes",
      "Art/Drawing Classes",
      "Coding/Programming Classes",
    ],
  },
  {
    name: "Technology Services",
    subcategories: [
      "Computer Repair",
      "Mobile Phone Repair",
      "Software Development",
      "IT Support",
      "Web Design/Development",
    ],
  },
  {
    name: "Event Services",
    subcategories: [
      "Photography",
      "Catering",
      "Event Planning",
      "DJ Services",
      "Decorations",
    ],
  },
  {
    name: "Delivery Services",
    subcategories: [
      "Courier Services",
      "Food Delivery",
      "Grocery Delivery",
      "Laundry Pickup/Delivery",
    ],
  },
  {
    name: "Legal & Financial Services",
    subcategories: [
      "Tax Preparation",
      "Legal Consultation",
      "Accounting/Bookkeeping",
      "Notary Services",
      "Insurance Services",
    ],
  },
  {
    name: "Miscellaneous Services",
    subcategories: [
      "Pet Grooming",
      "Personal Shopping",
      "Courier Services",
      "Freelance Writing/Editing",
      "Custom Tailoring",
    ],
  },
];