export const serviceCategories = [
  {
    name: "Automotive Services",
    subcategories: [
      "Battery Replacement",
      "Oil Change",
      "Tire Services",
      "Car Wash & Detailing",
      "Engine Repair",
      "Brake Services",
      "AC Repair",
      "Towing Services",
    ],
  },
  {
    name: "Home Services",
    subcategories: [
      "Plumbing",
      "Electrical",
      "Carpentry",
      "Painting",
      "Cleaning Services",
      "Pest Control",
      "Landscaping",
      "Moving Services",
    ],
  },
  {
    name: "Personal Services",
    subcategories: [
      "Hair Styling",
      "Makeup & Beauty",
      "Spa & Massage",
      "Fitness Training",
      "Photography",
      "Videography",
      "Event Planning",
      "Catering",
    ],
  },
  {
    name: "Professional Services",
    subcategories: [
      "Legal Services",
      "Accounting",
      "Consulting",
      "Marketing",
      "Web Development",
      "Graphic Design",
      "Content Writing",
      "Translation",
    ],
  },
  {
    name: "Educational Services",
    subcategories: [
      "Tutoring",
      "Music Lessons",
      "Dance Classes",
      "Art Classes",
      "Language Classes",
      "Computer Training",
      "Vocational Training",
      "Exam Preparation",
    ],
  },
  {
    name: "Health & Wellness",
    subcategories: [
      "Medical Consultation",
      "Nursing Care",
      "Physiotherapy",
      "Nutrition Counseling",
      "Mental Health Counseling",
      "Yoga Classes",
      "Meditation Sessions",
      "Alternative Medicine",
    ],
  },
  {
    name: "Technical Services",
    subcategories: [
      "Computer Repair",
      "Phone Repair",
      "Appliance Repair",
      "IT Support",
      "Network Installation",
      "Software Installation",
      "Data Recovery",
      "Electronics Repair",
    ],
  },
  {
    name: "Delivery & Logistics",
    subcategories: [
      "Courier Services",
      "Errand Running",
      "Grocery Delivery",
      "Food Delivery",
      "Package Delivery",
      "Freight Services",
      "Moving & Packing",
      "Same-Day Delivery",
    ],
  },
  {
    name: "Pet Services",
    subcategories: [
      "Pet Grooming",
      "Dog Walking",
      "Pet Sitting",
      "Veterinary Services",
      "Pet Training",
      "Pet Photography",
      "Pet Transportation",
      "Pet Boarding",
    ],
  },
  {
    name: "Others",
    subcategories: [
      "Equipment Rental",
      "Laundry Services",
      "Tailoring",
      "Shoe Repair",
      "Key Cutting",
      "Notary Services",
      "Document Services",
      "Others",
    ],
  },
];
